version: '3.1'

services:

  application:
    image: mikhailtarasevich/worker-data-app
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/worker_data_db
    ports:
      - 8888:8888
    networks:
      - network

  postgres:
    image: mikhailtarasevich/worker-data-db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: postgres
      POSTGRES_DB: worker_data_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5050:5432
    restart: always
    networks:
      - network

volumes:
  postgres:

networks:
  network:
    driver: bridge